//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Menu"",
            ""id"": ""de14ebf8-ba8f-4b89-99ca-681af0287c57"",
            ""actions"": [
                {
                    ""name"": ""Toggle Menu Screen"",
                    ""type"": ""Button"",
                    ""id"": ""affe604e-a2fc-4f98-8038-f428b1c9f1f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0ab1be56-3c13-40a7-88d2-ff93e3ded23d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Toggle Menu Screen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Developer"",
            ""id"": ""3dcc4b8d-92e7-4959-b42e-7465dbdc8a82"",
            ""actions"": [
                {
                    ""name"": ""Toggle Console"",
                    ""type"": ""Button"",
                    ""id"": ""e874a72c-8e3d-4ebd-8648-3ed69f0a6cf0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""441c3593-b766-4e5e-8bcb-450896c55e04"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Toggle Console"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player"",
            ""id"": ""c0864925-abf2-449f-9708-f60853523919"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""919d575b-7e20-4914-8158-7a6f9f6c9e90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""fd870bcf-7d90-4a8e-9f8b-a04f160f6486"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""20ca4e05-560d-4b3d-a298-bfc5e9252921"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9dc6fae3-62dc-4584-a81d-6013f9db9890"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0b2fe890-26f3-4cac-8cc0-4c71cc7614bf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1acb2c56-3b38-442c-820b-49e49d78a63c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""65275efe-027e-4313-879a-2eef7c16605d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e7844b47-3e73-4d69-ad3c-4ef4cd46fcc8"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BuildScreen"",
            ""id"": ""b461159a-ff9c-4e6c-9569-52ca5804e2c4"",
            ""actions"": [
                {
                    ""name"": ""Toggle Build Screen"",
                    ""type"": ""Button"",
                    ""id"": ""b8f90ab2-82ad-448a-b206-c4df3221d4f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape Build Screen"",
                    ""type"": ""Button"",
                    ""id"": ""ff660156-aaa5-4d1a-bb04-e6cba812f2b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click To Construct"",
                    ""type"": ""Button"",
                    ""id"": ""7ff678e0-e732-445e-bf16-4f3df274f5d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3fe7af2e-be7b-4a9c-bb20-27a399757025"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Toggle Build Screen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22399d30-dcaf-4a16-921b-1f080205c417"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Escape Build Screen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c09d36d-db46-46a4-bacd-a5ae375852be"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Click To Construct"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MachineScreen"",
            ""id"": ""f9164149-132c-4be5-8180-4cb5203a003c"",
            ""actions"": [
                {
                    ""name"": ""Open Machine Screen"",
                    ""type"": ""Button"",
                    ""id"": ""8a7ff586-880e-4121-aea8-2f7f7e198c07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape Machine Screen"",
                    ""type"": ""Button"",
                    ""id"": ""575828f5-75c2-4311-862f-466e5a96cce3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dde01ba0-2688-4933-a1e4-9832988cda5b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Escape Machine Screen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36f0947d-f861-48ed-8486-521daaaa86ee"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Open Machine Screen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_ToggleMenuScreen = m_Menu.FindAction("Toggle Menu Screen", throwIfNotFound: true);
        // Developer
        m_Developer = asset.FindActionMap("Developer", throwIfNotFound: true);
        m_Developer_ToggleConsole = m_Developer.FindAction("Toggle Console", throwIfNotFound: true);
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Inventory = m_Player.FindAction("Inventory", throwIfNotFound: true);
        // BuildScreen
        m_BuildScreen = asset.FindActionMap("BuildScreen", throwIfNotFound: true);
        m_BuildScreen_ToggleBuildScreen = m_BuildScreen.FindAction("Toggle Build Screen", throwIfNotFound: true);
        m_BuildScreen_EscapeBuildScreen = m_BuildScreen.FindAction("Escape Build Screen", throwIfNotFound: true);
        m_BuildScreen_ClickToConstruct = m_BuildScreen.FindAction("Click To Construct", throwIfNotFound: true);
        // MachineScreen
        m_MachineScreen = asset.FindActionMap("MachineScreen", throwIfNotFound: true);
        m_MachineScreen_OpenMachineScreen = m_MachineScreen.FindAction("Open Machine Screen", throwIfNotFound: true);
        m_MachineScreen_EscapeMachineScreen = m_MachineScreen.FindAction("Escape Machine Screen", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_ToggleMenuScreen;
    public struct MenuActions
    {
        private @InputMaster m_Wrapper;
        public MenuActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleMenuScreen => m_Wrapper.m_Menu_ToggleMenuScreen;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @ToggleMenuScreen.started += instance.OnToggleMenuScreen;
            @ToggleMenuScreen.performed += instance.OnToggleMenuScreen;
            @ToggleMenuScreen.canceled += instance.OnToggleMenuScreen;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @ToggleMenuScreen.started -= instance.OnToggleMenuScreen;
            @ToggleMenuScreen.performed -= instance.OnToggleMenuScreen;
            @ToggleMenuScreen.canceled -= instance.OnToggleMenuScreen;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // Developer
    private readonly InputActionMap m_Developer;
    private List<IDeveloperActions> m_DeveloperActionsCallbackInterfaces = new List<IDeveloperActions>();
    private readonly InputAction m_Developer_ToggleConsole;
    public struct DeveloperActions
    {
        private @InputMaster m_Wrapper;
        public DeveloperActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleConsole => m_Wrapper.m_Developer_ToggleConsole;
        public InputActionMap Get() { return m_Wrapper.m_Developer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DeveloperActions set) { return set.Get(); }
        public void AddCallbacks(IDeveloperActions instance)
        {
            if (instance == null || m_Wrapper.m_DeveloperActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DeveloperActionsCallbackInterfaces.Add(instance);
            @ToggleConsole.started += instance.OnToggleConsole;
            @ToggleConsole.performed += instance.OnToggleConsole;
            @ToggleConsole.canceled += instance.OnToggleConsole;
        }

        private void UnregisterCallbacks(IDeveloperActions instance)
        {
            @ToggleConsole.started -= instance.OnToggleConsole;
            @ToggleConsole.performed -= instance.OnToggleConsole;
            @ToggleConsole.canceled -= instance.OnToggleConsole;
        }

        public void RemoveCallbacks(IDeveloperActions instance)
        {
            if (m_Wrapper.m_DeveloperActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDeveloperActions instance)
        {
            foreach (var item in m_Wrapper.m_DeveloperActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DeveloperActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DeveloperActions @Developer => new DeveloperActions(this);

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Inventory;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Inventory => m_Wrapper.m_Player_Inventory;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Inventory.started += instance.OnInventory;
            @Inventory.performed += instance.OnInventory;
            @Inventory.canceled += instance.OnInventory;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Inventory.started -= instance.OnInventory;
            @Inventory.performed -= instance.OnInventory;
            @Inventory.canceled -= instance.OnInventory;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // BuildScreen
    private readonly InputActionMap m_BuildScreen;
    private List<IBuildScreenActions> m_BuildScreenActionsCallbackInterfaces = new List<IBuildScreenActions>();
    private readonly InputAction m_BuildScreen_ToggleBuildScreen;
    private readonly InputAction m_BuildScreen_EscapeBuildScreen;
    private readonly InputAction m_BuildScreen_ClickToConstruct;
    public struct BuildScreenActions
    {
        private @InputMaster m_Wrapper;
        public BuildScreenActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleBuildScreen => m_Wrapper.m_BuildScreen_ToggleBuildScreen;
        public InputAction @EscapeBuildScreen => m_Wrapper.m_BuildScreen_EscapeBuildScreen;
        public InputAction @ClickToConstruct => m_Wrapper.m_BuildScreen_ClickToConstruct;
        public InputActionMap Get() { return m_Wrapper.m_BuildScreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildScreenActions set) { return set.Get(); }
        public void AddCallbacks(IBuildScreenActions instance)
        {
            if (instance == null || m_Wrapper.m_BuildScreenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BuildScreenActionsCallbackInterfaces.Add(instance);
            @ToggleBuildScreen.started += instance.OnToggleBuildScreen;
            @ToggleBuildScreen.performed += instance.OnToggleBuildScreen;
            @ToggleBuildScreen.canceled += instance.OnToggleBuildScreen;
            @EscapeBuildScreen.started += instance.OnEscapeBuildScreen;
            @EscapeBuildScreen.performed += instance.OnEscapeBuildScreen;
            @EscapeBuildScreen.canceled += instance.OnEscapeBuildScreen;
            @ClickToConstruct.started += instance.OnClickToConstruct;
            @ClickToConstruct.performed += instance.OnClickToConstruct;
            @ClickToConstruct.canceled += instance.OnClickToConstruct;
        }

        private void UnregisterCallbacks(IBuildScreenActions instance)
        {
            @ToggleBuildScreen.started -= instance.OnToggleBuildScreen;
            @ToggleBuildScreen.performed -= instance.OnToggleBuildScreen;
            @ToggleBuildScreen.canceled -= instance.OnToggleBuildScreen;
            @EscapeBuildScreen.started -= instance.OnEscapeBuildScreen;
            @EscapeBuildScreen.performed -= instance.OnEscapeBuildScreen;
            @EscapeBuildScreen.canceled -= instance.OnEscapeBuildScreen;
            @ClickToConstruct.started -= instance.OnClickToConstruct;
            @ClickToConstruct.performed -= instance.OnClickToConstruct;
            @ClickToConstruct.canceled -= instance.OnClickToConstruct;
        }

        public void RemoveCallbacks(IBuildScreenActions instance)
        {
            if (m_Wrapper.m_BuildScreenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBuildScreenActions instance)
        {
            foreach (var item in m_Wrapper.m_BuildScreenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BuildScreenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BuildScreenActions @BuildScreen => new BuildScreenActions(this);

    // MachineScreen
    private readonly InputActionMap m_MachineScreen;
    private List<IMachineScreenActions> m_MachineScreenActionsCallbackInterfaces = new List<IMachineScreenActions>();
    private readonly InputAction m_MachineScreen_OpenMachineScreen;
    private readonly InputAction m_MachineScreen_EscapeMachineScreen;
    public struct MachineScreenActions
    {
        private @InputMaster m_Wrapper;
        public MachineScreenActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenMachineScreen => m_Wrapper.m_MachineScreen_OpenMachineScreen;
        public InputAction @EscapeMachineScreen => m_Wrapper.m_MachineScreen_EscapeMachineScreen;
        public InputActionMap Get() { return m_Wrapper.m_MachineScreen; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MachineScreenActions set) { return set.Get(); }
        public void AddCallbacks(IMachineScreenActions instance)
        {
            if (instance == null || m_Wrapper.m_MachineScreenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MachineScreenActionsCallbackInterfaces.Add(instance);
            @OpenMachineScreen.started += instance.OnOpenMachineScreen;
            @OpenMachineScreen.performed += instance.OnOpenMachineScreen;
            @OpenMachineScreen.canceled += instance.OnOpenMachineScreen;
            @EscapeMachineScreen.started += instance.OnEscapeMachineScreen;
            @EscapeMachineScreen.performed += instance.OnEscapeMachineScreen;
            @EscapeMachineScreen.canceled += instance.OnEscapeMachineScreen;
        }

        private void UnregisterCallbacks(IMachineScreenActions instance)
        {
            @OpenMachineScreen.started -= instance.OnOpenMachineScreen;
            @OpenMachineScreen.performed -= instance.OnOpenMachineScreen;
            @OpenMachineScreen.canceled -= instance.OnOpenMachineScreen;
            @EscapeMachineScreen.started -= instance.OnEscapeMachineScreen;
            @EscapeMachineScreen.performed -= instance.OnEscapeMachineScreen;
            @EscapeMachineScreen.canceled -= instance.OnEscapeMachineScreen;
        }

        public void RemoveCallbacks(IMachineScreenActions instance)
        {
            if (m_Wrapper.m_MachineScreenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMachineScreenActions instance)
        {
            foreach (var item in m_Wrapper.m_MachineScreenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MachineScreenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MachineScreenActions @MachineScreen => new MachineScreenActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IMenuActions
    {
        void OnToggleMenuScreen(InputAction.CallbackContext context);
    }
    public interface IDeveloperActions
    {
        void OnToggleConsole(InputAction.CallbackContext context);
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
    }
    public interface IBuildScreenActions
    {
        void OnToggleBuildScreen(InputAction.CallbackContext context);
        void OnEscapeBuildScreen(InputAction.CallbackContext context);
        void OnClickToConstruct(InputAction.CallbackContext context);
    }
    public interface IMachineScreenActions
    {
        void OnOpenMachineScreen(InputAction.CallbackContext context);
        void OnEscapeMachineScreen(InputAction.CallbackContext context);
    }
}
